dist: focal
language: python
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
    - libxcb-randr0-dev
    - libxcb-xtest0-dev
    - libxcb-xinerama0-dev
    - libxcb-shape0-dev
    - libxcb-xkb-dev
    - libxcb-render-util0
    - libxcb-icccm4
    - libxcb-keysyms1
    - libxcb-image0
os:
  - linux

addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0

services: xvfb

python:
  - "3.8"
variables:
  QT_QPA_PLATFORM: "offscreen"



# command to install dependencies
install:
  - pip install PySide2
  - make install_deps

# command to run tests
script:
  - python -m pytest tests/core/ -vv
  - make coverage 
  - bash <(curl -s https://codecov.io/bash)
