site_name: Cutevariant Doc
site_author: Sacha Schutz, Charles Monod-Broca
site_description: >-
  Find the documentation of cutevariant, with material for both developers and geneticians !
  You will find how to use cutevariant, tips and tricks, and if you're a developer wishing to contribute,
  here you will find a complete API reference to add features to cutevariant.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: 'assets/favicon.png'
  logo: 'assets/favicon.png'
markdown_extensions:
- footnotes
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- pymdownx.highlight
- pymdownx.superfences
- admonition
plugins:
  - search
  - mkdocstrings

# Setting up the headers
nav:
    - Home: 'index.md'
    - Getting started:
      - Installation: 'installation.md'
      - Quick start: 'quick-start.md'
    - Examples:
      - Find CFTR tutorial (basic): 'tutorials/basic-tutorial.md'
      - Add annotation reference database (intermediate): 'tutorials/add-annotation-reference.md'
    - Documentation:
      - Plugins:
        - Fields : 'plugins/fields.md'
        - Filters : 'plugins/filters.md'
        - Wordsets : 'plugins/wordset.md'
        - Selections : 'plugins/selections.md'
        - Gene viewer : 'plugins/gene-viewer.md'
        - Variant view : 'plugins/variant-view.md'
        - VQL editor : 'plugins/vql-editor.md'
      - VQL: 'vql.md'
    - Developer:
      - Installation: 'developer/install-for-dev.md'
      - Customization:
        - Create a plugin: 'developer/customization/create-plugin.md'
        - Create a formatter: 'developer/customization/create-formatter.md'
        - Create a writer: 'developer/customization/create-writer.md'
        - Create a reader: 'developer/customization/create-reader.md'
      - API Documentation:
        - Core classes:
          - SQL: 'developer/api-documentation/sql-module-doc.md'
          # - VQL: ''
          # - Readers:
          #   - Abstract Reader: ''
          #   - Annotation Parser: ''
          #   - Bed Reader: ''
          #   - CSV Reader: ''
          #   - Fake Reader: ''
          #   - Ped Reader: ''
          #   - VCF Reader: ''
          # - Writers:
          #   - Abstract Writer: ''
          #   - Bed Writer: ''
          #   - CSV Writer: ''
          #   - Ped Writer: ''
          #   - VCF Writer: ''
        - GUI classes: 'developer/api-documentation/gui-classes.md'

repo_url: "https://github.com/labsquare/cutevariant"
