site_name: Cutevariant
site_author: Sacha Schutz, Charles Monod-Broca
site_description: >-
  Cutevariant is a cross-plateform application dedicated to maniupulate and filter variation 
  from annotated VCF file. Here you will find documentation for both user and developers wishing to contribute,


# Setting up the headers
nav:
    - Home: 'index.md'
    - Getting started: 
      - Introduction: 'introduction.md'
      - Installation: 'installation.md'
      - Quick start: 'quick-start.md'
      - Examples: 'tutorials/basic-tutorial.md'
    
    - Documentation:
      - VQL query: 'vql.md'
      - Plugins:
        - Fields : 'plugins/fields.md'
        - Source : 'plugins/selections.md'
        - Filters : 'plugins/filters.md'
        - Variant view : 'plugins/variant-view.md'
        - Wordsets : 'plugins/wordset.md'

    - Developer:
      - Setup environment: 'developer/install-for-dev.md'
      - Database: 'developer/customization/database.md'
      - Create a plugin: 'developer/customization/create-plugin.md'
      - Create a formatter: 'developer/customization/create-formatter.md'
      - Create a writer: 'developer/customization/create-writer.md'
      - Create a reader: 'developer/customization/create-reader.md'
      - GUI classes: 'developer/api-documentation/gui-classes.md'
      # - API Documentation:
      #   - Core classes:
          # - SQL: 'developer/api-documentation/sql.md'
          # - VQL: 'developer/api-documentation/vql.md'
          # - Reader: 'developer/api-documentation/reader.md'
          # - Writer: 'developer/api-documentation/writer.md'
          # - VQL: ''
          # - Readers:
          #   - Abstract Reader: ''
          #   - Annotation Parser: ''
          #   - Bed Reader: ''
          #   - CSV Reader: ''
          #   - Fake Reader: ''
          #   - Ped Reader: ''
          #   - VCF Reader: ''
          # - Writers:
          #   - Abstract Writer: ''
          #   - Bed Writer: ''
          #   - CSV Writer: ''
          #   - Ped Writer: ''
          #   - VCF Writer: ''


extra_css:
  - stylesheets/extra.css

theme:
  name: material

  custom_dir: docs/theme_override_home/
  include_search_page: false
  search_index_only: true

  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # toggle:
      #   icon: material/toggle-switch-off-outline
      #   name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
  favicon: 'assets/favicon.png'
  logo: 'assets/icon_white.png'
markdown_extensions:
- footnotes
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- pymdownx.highlight
- pymdownx.superfences
- admonition


plugins:
  - search
  - mkdocstrings

repo_url: "https://github.com/labsquare/cutevariant"
