name: Release

  
# when it active ? 
on: 
  push:
    tags:
      - '*'
    branches:
      - master

jobs:

  # WINDOWS JOB 
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture: ['x64', 'x86']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: ${{matrix.architecture}}
      - name: install_deps
        run: "make install_deps"
      - name: install PySide2    # Parce que @ysard veut absolument les version deprecated
        run : pip install PySide2
      - name: install windows deps 
        run: |
            pip install pywin32
            pip install PyInstaller==4.0
      - name: test
        run: python -m pytest tests/core

      - name: create binary 
        run: pyinstaller -i icon.ico --name="cutevariant_${{matrix.architecture}}" --hidden-import json --add-data "cutevariant;cutevariant" cutevariant\__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cutevariant-standalone-${{matrix.architecture}}
          path: dist
      - name: Create release 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cutevariant-standalone*"
          token: ${{secrets.GITHUB_TOKEN}}




  # MAC OS JOB 

  # Macos:
  #   runs-on: macOS-latest
  #   if: "contains(github.event.head_commit.message, '[deploy]')"
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.8'
  #     - name: install_deps
  #       run: "make install"
  #     - name: install PySide2    # Parce que @ysard veut absolument les version deprecated
  #       run : pip install PySide2
  #     - name: install mac deps 
  #       run: |
  #           pip install PyInstaller==4.0
  #     - name: create binary 
  #       run: pyinstaller -i icon.ico --name="cutevariant" --add-data cutevariant:cutevariant cutevariant/__main__.py;ls
