name: Test

# when it active ? 
on: 
  workflow_dispatch:
    inputs:
      name:
        description: "run name"
        default: "default"
  push:
    branches:
      - devel
      - github-ci
 
  pull_request:
    branches:
      - devel

jobs:
  
  # LINUX JOB 
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.10.2']
    steps:
      - uses: actions/checkout@v2
      - name: Install OS dependencies
        run: |
            sudo apt-get update -yy
            sudo apt-get install -yy \
              libxkbcommon-x11-0 \
              libxkbcommon0 \
              libxkbcommon-dev \
              libxcb-icccm4 \
              libxcb-image0 \
              libxcb-shm0 \
              libxcb-keysyms1 \
              libxcb-randr0 \
              libxcb-render-util0 \
              libxcb-render0 \
              libxcb-shape0 \
              libxcb-sync1 \
              libxcb-xfixes0 \
              libxcb-xinerama0 \
              libxcb-xkb1 \
              libxcb1 
            #export QT_QPA_PLATFORM=offscreen
            export DISPLAY=:99.0
      - name: Install OpenGL
        run: sudo apt-get install libgl1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python_version}}
      - name: install_deps
        run: "make install_deps"
      - name: install PySide6    # Parce que @ysard veut absolument les version deprecated
        run : pip install PySide6
      - name: test 
        run: xvfb-run -a python -m pytest tests/core

  # WINDOWS JOB 

  # windows:
  #   runs-on: windows-latest

  #   strategy:
  #     matrix:
  #       architecture: ['x64', 'x86']
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.9'
  #         architecture: ${{matrix.architecture}}
  #     - name: install_deps
  #       run: "make install_deps"
  #     - name: install PySide6    # Parce que @ysard veut absolument les version deprecated
  #       run : pip install PySide6
  #     - name: install windows deps 
  #       run: |
  #           pip install pywin32
  #           pip install PyInstaller==4.0
  #     - name: test
  #       run: python -m pytest tests/core

  #     - name: create binary 
  #       if: contains(github.event.head_commit.message, '[deploy]')  
  #       run: pyinstaller -i icon.ico --name="cutevariant_${{matrix.architecture}}" --hidden-import json --add-data "cutevariant;cutevariant" cutevariant\__main__.py

  #     - name: Upload artifact
  #       if: github.ref == 'refs/heads/master' || contains(github.event.head_commit.message, '[deploy]')  
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: cutevariant-standalone-${{matrix.architecture}}
  #         path: dist




